<a href="https://colab.research.google.com/github/Bhavanareddy0510/pytorch-tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**list**

**one dimension array**

In [ ]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

** **two dimension array**

In [ ]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**numpy arrays**

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.78232732, 0.48387056, 0.87752638, 0.99646149],
       [0.10212474, 0.51739299, 0.66048804, 0.03200676],
       [0.06776776, 0.46090862, 0.35834401, 0.59393545]])

In [ ]:
np1.dtype

dtype('float64')

**tensor**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**create tensor out of numpy array**

In [ ]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.7823, 0.4839, 0.8775, 0.9965],
        [0.1021, 0.5174, 0.6605, 0.0320],
        [0.0678, 0.4609, 0.3583, 0.5939]], dtype=torch.float64)