<a href="https://colab.research.google.com/github/Bhavanareddy0510/pytorch-tutorial/blob/main/tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#reshape and view
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(18)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [12]:
my_torch2 = my_torch2.reshape(6,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [16]:
my_torch3 = torch.arange(6)
my_torch3

tensor([0, 1, 2, 3, 4, 5])

In [17]:
my_torch4 = my_torch3.view(2,3)
my_torch4

tensor([[0, 1, 2],
        [3, 4, 5]])

In [18]:
#with reshape nd view they will update
my_torch5 = torch.arange(10)
my_torch5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_torch5[2] = 432
my_torch5

tensor([  0,   1, 432,   3,   4,   5,   6,   7,   8,   9])

In [21]:
my_torch6

tensor([[  0,   1, 432,   3,   4],
        [  5,   6,   7,   8,   9]])

In [22]:
#slices
my_torch7 = torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#grab a specific item
my_torch7[7]

tensor(7)

In [25]:
#grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [29]:
#return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])