<a href="https://colab.research.google.com/github/Bhavanareddy0510/pytorch-tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [6]:
#addition longhand
torch.add(tensor_a , tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [10]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
torch.mul(tensor_a , tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
#divison
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
#divison longhand
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
#remmainder modules
tensor_b % tensor_a


tensor([0, 0, 1, 0])

In [17]:
#remainder longhand
torch.remainder(tensor_b , tensor_a)


tensor([0, 0, 1, 0])

In [18]:
#exponents/power
torch.pow(tensor_a , tensor_b)


tensor([    1,    64,  2187, 65536])

In [19]:
#another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
tensor_b.sub(tensor_a)

tensor([4, 4, 4, 4])

In [21]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [22]:
tensor_b.div(tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [23]:
tensor_b.remainder(tensor_a)

tensor([0, 0, 1, 0])

In [26]:
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [27]:
#reaasignmnet
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([1, 2, 3, 4])

In [29]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
tensor_a

tensor([ 6,  8, 10, 12])